SELECT T2.SUB_ID,T2.LOCATION_ID,SUM(T2.TIME_DIFF),MIN(T2.TIME_DIFF),MAX(T2.TIME_DIFF)
FROM
(
SELECT T1.SUB_ID,T1.LOCATION_ID,(unix_timestamp(T1.STARTDATETIME)-unix_timestamp(T1.TS1))/60 as TIME_DIFF
FROM
(
SELECT SUB_ID,LOCATION_ID,STARTDATETIME,LEAD(STARTDATETIME,1,"01/03/2017 13:00") OVER(PARTION BY SUB_ID,LOCATION_ID ORDER BY STARTDATETIME) AS TS1
FROM TELCO_DATA
) T1
) as T2
WHERE GROUP BY T2.SUB_ID,T2.LOCATION_ID;
